"""Read-only: per-ruleset installed / missing / drifted; optional STATE.md."""

from __future__ import annotations

import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from forge import EXIT_OK, TAG_RULESET_NAME, branch_ruleset_name
from forge.apply import (
    DEFAULT_API,
    ForgeError,
    GitHubClient,
    UrlOpen,
    build_payloads,
    classify_ruleset,
    expected_ruleset_names,
    find_named_ruleset,
    load_config,
    parse_repo,
    resolve_token,
)

EXIT_STATE = 2
GENERATED_HEADER = "<!-- generated by forge status; do not edit -->"
MISSING_TOKEN_NOTE = "未查询：缺 FORGE_GITHUB_TOKEN"


def _git(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True,
        text=True,
        check=False,
    )


def git_describe(root: Path) -> str:
    proc = _git(root, "describe", "--tags", "--always")
    if proc.returncode == 0 and proc.stdout.strip():
        return proc.stdout.strip()
    return "(unknown)"


def git_latest_tag(root: Path) -> str:
    proc = _git(root, "describe", "--tags", "--abbrev=0")
    if proc.returncode == 0 and proc.stdout.strip():
        return proc.stdout.strip()
    return "(none)"


def list_recent_tags(root: Path, limit: int = 8) -> list[str]:
    proc = _git(root, "tag", "--sort=-creatordate")
    if proc.returncode != 0:
        return []
    tags = [line.strip() for line in proc.stdout.splitlines() if line.strip()]
    return tags[:limit]


def scan_ci_job_names(root: Path) -> list[str]:
    """Job ids (or their `name:`) across .github/workflows — the strings a PR check shows.

    Workflow-level `name:` and step `- name:` are not check names.
    """
    folder = root / ".github" / "workflows"
    if not folder.is_dir():
        return []
    try:
        import yaml
    except ImportError:  # pragma: no cover
        return []
    names: list[str] = []
    seen: set[str] = set()
    for path in sorted(list(folder.glob("*.yml")) + list(folder.glob("*.yaml"))):
        try:
            data = yaml.safe_load(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        jobs = data.get("jobs") if isinstance(data, dict) else None
        if not isinstance(jobs, dict):
            continue
        for job_id, job in jobs.items():
            label = job.get("name") if isinstance(job, dict) and isinstance(job.get("name"), str) else str(job_id)
            if label and label not in seen:
                seen.add(label)
                names.append(label)
    return names


def required_checks_by_branch(config: Any) -> dict[str, list[str]]:
    return {branch: config.rule_for(branch).required_checks for branch in config.protect}


def fetch_ruleset_details(
    client: GitHubClient,
    owner: str,
    name: str,
    listed: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    details: list[dict[str, Any]] = []
    for item in listed:
        detail = item
        ruleset_id = item.get("id")
        if ruleset_id is not None:
            try:
                detail = client.get_ruleset(owner, name, int(ruleset_id))
            except ForgeError:
                detail = item
        details.append(detail)
    return details


def classify_all(
    config: Any,
    installed: list[dict[str, Any]],
) -> list[tuple[str, str]]:
    expected = {payload["name"]: payload for payload in build_payloads(config)}
    by_name = {item.get("name"): item for item in installed if isinstance(item.get("name"), str)}
    rows: list[tuple[str, str]] = []
    for name in expected_ruleset_names(config):
        rows.append((name, classify_ruleset(expected[name], by_name.get(name))))
    return rows


def render_status_lines(
    *,
    config: Any,
    rows: list[tuple[str, str]] | None,
    token_missing: bool,
) -> list[str]:
    lines: list[str] = []
    if token_missing:
        for name in expected_ruleset_names(config):
            lines.append(f"{name}: {MISSING_TOKEN_NOTE}")
        return lines
    assert rows is not None
    for name, state in rows:
        lines.append(f"{name}: {state}")
    return lines


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def render_state_markdown(
    *,
    root: Path,
    config: Any,
    rows: list[tuple[str, str]] | None,
    token_missing: bool,
    generated_at: str | None = None,
    promote_note: str = "",
) -> str:
    pin = git_describe(root)
    latest = git_latest_tag(root)
    tags = list_recent_tags(root)
    jobs = scan_ci_job_names(root)
    stamp = generated_at or utc_now()
    lines = [
        GENERATED_HEADER,
        f"<!-- generated: {stamp} -->",
        "",
        "# 仓库状态",
        "",
        "## Pin",
        "",
        f"`{pin}`（最近 tag `{latest}`）",
        "",
        "## 保护分支",
        "",
    ]
    for branch in config.protect:
        rule = config.rule_for(branch)
        owners = "true" if rule.code_owners else "false"
        checks = ", ".join(rule.required_checks) if rule.required_checks else "(none)"
        extra = f"；promote_from={rule.promote_from}" if rule.promote_from else ""
        lines.append(
            f"- `{branch}`：required_checks=[{checks}]；approvals={rule.approvals}；code_owners={owners}{extra}"
        )
    lines.extend(["", "## Ruleset", ""])
    if token_missing:
        for name in expected_ruleset_names(config):
            lines.append(f"- `{name}`：{MISSING_TOKEN_NOTE}")
    else:
        assert rows is not None
        for name, state in rows:
            lines.append(f"- `{name}`：{state}")
    lines.extend(["", "## Required checks", ""])
    for branch, checks in required_checks_by_branch(config).items():
        shown = ", ".join(checks) if checks else "(none)"
        lines.append(f"- `{branch}`：{shown}")
    lines.extend(["", "## CI job 名", ""])
    if jobs:
        for job in jobs:
            lines.append(f"- `{job}`")
    else:
        lines.append("- （未发现 `.github/workflows/*.yml`）")
    lines.extend(["", "## 最近 tag", ""])
    if tags:
        for tag in tags:
            lines.append(f"- `{tag}`")
    else:
        lines.append("- （无）")
    lines.extend(["", "## 开放的 promote PR", ""])
    lines.append(promote_note or (MISSING_TOKEN_NOTE if token_missing else "（无）"))
    lines.append("")
    return "\n".join(lines) + "\n"


def parse_state_protect(text: str) -> list[str]:
    branches: list[str] = []
    in_section = False
    for line in text.splitlines():
        if line.strip() == "## 保护分支":
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if in_section and line.startswith("- `"):
            name = line.split("`", 2)[1]
            branches.append(name)
    return branches


def parse_state_required_checks(text: str) -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    in_section = False
    for line in text.splitlines():
        if line.strip() == "## Required checks":
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if in_section and line.startswith("- `"):
            # - `main`：unit, lint
            try:
                name = line.split("`", 2)[1]
                rest = line.split("：", 1)[1].strip()
            except IndexError:
                continue
            if rest == "(none)":
                out[name] = []
            else:
                out[name] = [part.strip() for part in rest.split(",") if part.strip()]
    return out


def parse_state_latest_tag(text: str) -> str | None:
    for line in text.splitlines():
        if "最近 tag" in line and "`" in line:
            parts = line.split("`")
            if len(parts) >= 4:
                return parts[3]
            if len(parts) >= 2:
                return parts[1]
    return None


def parse_state_ci_jobs(text: str) -> list[str] | None:
    lines = text.splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == "## CI job 名")
    except StopIteration:
        return None
    jobs: list[str] = []
    for line in lines[start + 1 :]:
        if line.startswith("## "):
            break
        stripped = line.strip()
        if stripped.startswith("- `") and stripped.endswith("`"):
            jobs.append(stripped[3:-1])
    return jobs


def state_is_fresh(root: Path, config: Any, text: str) -> tuple[bool, str]:
    if GENERATED_HEADER not in text:
        return False, "missing generated header; 运行 forge status --write"
    protect = parse_state_protect(text)
    if protect != list(config.protect):
        return False, "保护分支与 forge.yaml 不一致；运行 forge status --write"
    recorded = parse_state_required_checks(text)
    expected = required_checks_by_branch(config)
    if recorded != expected:
        return False, "required checks 与 forge.yaml 不一致；运行 forge status --write"
    # The pin / latest tag is informational only: the release commit carries
    # STATE.md and is tagged afterwards, so comparing tags would redden every
    # release. CI job names are compared instead (they live in the tree).
    recorded_jobs = parse_state_ci_jobs(text)
    if recorded_jobs is not None and recorded_jobs != scan_ci_job_names(root):
        return False, "CI job 名与 .github/workflows 不一致；运行 forge status --write"
    return True, "ok"


def list_open_promote_prs(
    client: GitHubClient,
    owner: str,
    name: str,
    config: Any,
) -> str:
    notes: list[str] = []
    for branch in config.protect:
        rule = config.rule_for(branch)
        if not rule.promote_from:
            continue
        listed = client.request(
            "GET",
            f"/repos/{owner}/{name}/pulls?state=open&head={owner}:{rule.promote_from}&base={branch}&per_page=10",
        )
        if not isinstance(listed, list) or not listed:
            continue
        for item in listed:
            if not isinstance(item, dict):
                continue
            number = item.get("number")
            title = item.get("title") or ""
            notes.append(f"- #{number} {title}".strip())
    return "\n".join(notes) if notes else "（无）"


def run_status(
    *,
    repo: str,
    token: str | None = None,
    urlopen: UrlOpen | None = None,
    base_url: str = DEFAULT_API,
    stdout: Any = None,
    stderr: Any = None,
    environ: dict[str, str] | os._Environ[str] | None = None,
    root: Path | str | None = None,
    path: Path | str | None = None,
    write: Path | str | None = None,
    check_state: bool = False,
) -> int:
    out = sys.stdout if stdout is None else stdout
    err = sys.stderr if stderr is None else stderr
    try:
        owner, name = parse_repo(repo)
        workshop = Path(root) if root is not None else Path(".")
        config_path = Path(path) if path is not None else (workshop / "forge.yaml")
        config = load_config(config_path if config_path.is_file() else None)
        resolved = token if token is not None else resolve_token(environ)
        token_missing = not bool(resolved)
        rows: list[tuple[str, str]] | None = None
        promote_note = MISSING_TOKEN_NOTE
        if not token_missing:
            client = GitHubClient(resolved or "", urlopen=urlopen, base_url=base_url)
            listed = fetch_ruleset_details(client, owner, name, client.list_rulesets(owner, name))
            rows = classify_all(config, listed)
            try:
                promote_note = list_open_promote_prs(client, owner, name, config)
            except ForgeError:
                promote_note = "（查询失败）"
        for line in render_status_lines(config=config, rows=rows, token_missing=token_missing):
            print(line, file=out)
        if write is not None:
            target = Path(write)
            if not target.is_absolute():
                target = workshop / target
            text = render_state_markdown(
                root=workshop,
                config=config,
                rows=rows,
                token_missing=token_missing,
                promote_note=promote_note,
            )
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
            print(f"wrote {target.as_posix()}", file=out)
        if check_state:
            state_path = workshop / "docs" / "STATE.md"
            if not state_path.is_file():
                print("docs/STATE.md missing; 运行 forge status --write", file=err)
                return EXIT_STATE
            ok, message = state_is_fresh(workshop, config, state_path.read_text(encoding="utf-8"))
            if not ok:
                print(message, file=err)
                return EXIT_STATE
            print("docs/STATE.md: ok", file=out)
        return EXIT_OK
    except ForgeError as exc:
        print(exc.message, file=err)
        return exc.code
