#!/usr/bin/env python3
"""Generate docs/cli.md from argparse --help. No network. Standard library only."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "cli.md"


def _help(*module_and_args: str) -> str:
    env = os.environ.copy()
    env["PYTHONPATH"] = str(REPO)
    proc = subprocess.run(
        [sys.executable, "-m", *module_and_args, "--help"],
        cwd=REPO,
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )
    text = (proc.stdout or "") + (proc.stderr or "")
    return text.strip() + "\n"


def _subcommands(help_text: str) -> list[str]:
    """Read the {a,b,c} block from argparse usage."""
    names: list[str] = []
    for line in help_text.splitlines():
        start = line.find("{")
        end = line.find("}")
        if start != -1 and end > start:
            inner = line[start + 1 : end]
            for item in inner.split(","):
                name = item.strip()
                if name:
                    names.append(name)
            break
    # aliases like pr-title (title): keep first occurrence order, skip duplicates
    seen: set[str] = set()
    out: list[str] = []
    for name in names:
        if name not in seen:
            seen.add(name)
            out.append(name)
    return out


def build() -> str:
    forge_help = _help("forge")
    overlay_help = _help("overlay")
    parts: list[str] = [
        "<!-- generated by scripts/gen_cli_docs.py; do not edit -->",
        "",
        "# CLI",
        "",
        "由 `python -m forge --help`、各子命令 `--help`、`python -m overlay --help` 生成。",
        "W1/W2 合入后由集成者重跑 `python3 scripts/gen_cli_docs.py`。",
        "人手不要在 README / skill / 设计文档里抄子命令清单。",
        "",
        "## python -m forge",
        "",
        "```text",
        forge_help.rstrip(),
        "```",
        "",
    ]
    for name in _subcommands(forge_help):
        parts.extend(
            [
                f"## python -m forge {name}",
                "",
                "```text",
                _help("forge", name).rstrip(),
                "```",
                "",
            ]
        )
    parts.extend(
        [
            "## python -m overlay",
            "",
            "```text",
            overlay_help.rstrip(),
            "```",
            "",
        ]
    )
    # Overlay subcommands: spec only requires overlay --help; include them
    # so the page matches what agents actually type after W1 adds migrate.
    for name in _subcommands(overlay_help):
        parts.extend(
            [
                f"## python -m overlay {name}",
                "",
                "```text",
                _help("overlay", name).rstrip(),
                "```",
                "",
            ]
        )
    return "\n".join(parts).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Write docs/cli.md from --help output.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if docs/cli.md does not match current --help (no write)",
    )
    parser.add_argument(
        "--out",
        default=str(OUT),
        help="output path (default: docs/cli.md)",
    )
    args = parser.parse_args(argv)
    text = build()
    path = Path(args.out)
    if args.check:
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            sys.stderr.write("docs/cli.md is stale; run python3 scripts/gen_cli_docs.py\n")
            return 1
        sys.stdout.write("ok\n")
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    sys.stdout.write(f"wrote {path}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
